bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/AbstractTemplatesSelectionPage.java

Optimized new project creation wizard size. More picture below:
Here on the left is a new size, and on the right is an old size.
Tested both on windows 10 and macOS 10.15.7.

Optimized default wizard size

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/ListInstalledToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/messages.properties

Now List Installed tools action shows information dialog to the user when it's clicked before installed the tools (when tools are not installed and IDF_PATH is not set). The information dialog looks like this:
After clicking "Yes", the Install tools dialog will be open. 
Test case:
- Go to Preferences -> C/C++ -> Build -> Environment and click Restore Defaults to clean environment variables.
-  Now go to Help -> ESP-IDF Tools Manager -> List Installed Tools and in the information dialog that appears click on "Yes". 
-  After this, the Install Tools dialog will be open, where it's necessary to choose ESP-IDF, git, and python locations. 
-  After tools installation environment variables are set again, and "List Installed Tools" is providing information about installed tools. 
Tested on …

IEP 308 list installed tools show an information dialog when there is an error

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/SDKConfigJsonReader.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizard.java

Now after switching the target from esp32 to esp32s2, the java process is releasing the lock on sdkconfig.json file so it can be deleted and not cause a build error. 
However, if a whole directory "build" is deleted after switching the target on Windows 10 ( I don't have the same issue on macOS),  there are other issue: "CreateProcess error=267, The directory name is invalid”, when I'm trying to build a project. 
To fix it, in deleteDirectory function was added condition statement, which leaves an empty build directory in the end. 
With both of these changes, the problem with building projects after switching targets is gone on both Windows 10 and macOS.
Test case:
- build some project on esp32 launch target, then switch target on esp32s2, click "Yes" in IDF target changed dialog. After …

IEP-317 Fixing error jdk when not releasing sdkconfig.json after switching launch target

---

bundles/com.espressif.idf.core/META-INF/MANIFEST.MF
bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

These changes are fixing the "Build not configured correctly" problem after closing, renaming, and copy the project.
The user now is able to build the project after it was closed and reopened again. 
Test cases:
1. Create a new project, close and open it. Then click on the build button -> successfully built project.
2. You can close an already built project and reopen it. Then click on the build button -> since the project is already built, you will see "ninja: no work to do. Build complete " message

IEP-349 fixing Build not configured correctly error

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/Messages.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizard.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/messages.properties

Added option to delete a launch target:
after deleting, a launch target is still in the launch bar until the eclipse is not restarted. To inform the user about it, the information dialog was added: 
I

IEP-203 Can't delete a Launch Target

---

features/com.espressif.idf.feature/feature.xml

- Remove CDT CMake specific version from the list of required feature list

IEP-396: Eclipse 2021-03 support

---

bundles/com.espressif.idf.launch.serial.core/META-INF/MANIFEST.MF
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunch.java
bundles/com.espressif.idf.terminal.connector.serial/META-INF/MANIFEST.MF
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/connector/SerialConnector.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/connector/SerialPortHandler.java

https://jira.espressif.com:8443/browse/IEP-409
**Test Case:**
1. Build and flash an application
2. Open ESP-IDF serial terminal
3. The serial terminal should connect to the port and show serial output
4. Flash the application again - This should disconnect the port and stop printing the serial output, and once the flashing is over it should connect back to the serial port and start printing the serial output (This was not the case earlier, where we were unable to flash it again until we close the serial monitor window)

IEP-409: Handling port closing and opening on serial flash

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewComponentWizard.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewComponentWizardPage.java

Added a trigger that allows to rebuilding the project after adding a component.
Test case: 
- Create a new component in the already built project > rebuild the project > there is no "Unresolved inclusion" issue

IEP-405: Build/Index after creating a new component in the project 

---

bundles/com.espressif.idf.ui/plugin.xml
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/NewComponentHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/NewProjectHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/NewProjectHandlerUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/messages.properties
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewComponentMainWizard.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewIDFProjectWizard.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewIdfProjectMainWizard.java

Added validation check before allowing IDF project creation. Validation consists of checking if idf-tools install command were run from eclipse and checking the existence of environment variables (IDF_PATH and path). 
test cases: 
after reset environment variables or reset INSTALL_TOOLS_FLAG preference
- try to create new idf project from project explorer > right click > new or from File > new.
after click on "Yes" install tools dialog appears: 
- after the tools have been installed and the env variables have been set, project creation should be allowed.

IEP-310 Add validation checks before allowing IDF project creation

---

bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/Messages.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/messages.properties
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizardPage.java

Fixed selecting the wrong port after disconnecting the device.
test case:
connect the device and select the right port to it in the esp target configuration > quit the target configuration wizard > unplug the device and try to flash the project and you will see error msg: 
if we will go to the esp target wizard again, we will see an empty device:
if we connect our device again, we will be able to flash the project again without selecting a port.

IEP-389: Target configuration select wrong com port

---

releng/com.espressif.idf.target/com.espressif.idf.target.target

CMake4Eclipse Jfrog link is having monthly quota download issues hence moving to cloudsmith repository as suggested. This will fix the build issues we are having.
@sigmaaa @alirana01 FYI

IEP-439: replacing jfrog link with the cloudsmith artifactory link

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/utils/EspConfigParser.java

In the latest [openocd](https://github.com/espressif/openocd-esp32/releases/tag/v0.10.0-esp32-20210401)  "esp-config.json" file was added. We are using it to provide to the user the right interface/board in the debugger configurations tab. 
The right path to the esp-config.json was provided and combo elements for voltage, target
and board now is bigger, so the user is able to see the option he is selecting

IEP-461: provide the right path to the board/interface config file and update UI

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/NewProjectHandlerUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/messages.properties

different message when tools are not installed from Eclipse, example:

IEP-468: Сustomize the messages according to what is missing

---

bundles/com.espressif.idf.ui/OSGI-INF/l10n/bundle.properties
bundles/com.espressif.idf.ui/plugin.xml
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/PythonCleanCommandHandler.java

added python clean command:
to use this command go to Project explorer > right click on project.
Test cases:
1. Run command on a built project > command successfully executed
2. Run command on a new project > command successfully executed
3. Run command on a project without build directory > user will see a message in a console that build directory is missing, nothing to clean

IEP-465 UI menu for "idf.py python-clean" command

---

README.md
README_CN.md

This PR:
1. Added redirection between English and Chinese readme files at the beginning of the readme files;
2. Provided Chinese translation on how to switch between Chinese and English Eclipse plugin interfaces;
3. Adjusted the position where "changing language" is added in the table of contents.

Update readme files to include how to switch languages (IEP-477)

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/Messages.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/messages.properties

Added warning message if openOCD doesn't support jtag flashing:

IEP-476: Add warning message if openOCD doesn't support jtag flashing

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

We need to set INSTALL_TOOLS_FLAG when configuring paths for the first time with the offline installer

IEP-487: set up INSTALL_TOOL_FLAG during early startup

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/IDFDebugLaunchDescriptorType.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java

This PR relates to issues described here: https://github.com/espressif/idf-eclipse-plugin/issues/309
this PR fixes issue with failing indexer on change configuration. 
The second problem was that building in Debug Config fails. It happened because we were losing target after the eclipse restart. This problem was also fixed, now we are not losing target and after eclipse restart, the target bar is not missing for debug config. 
An additional fix for the NPE, when creating a new launch configuration was added. 
Tested on macOS and Windows 10. Test cases:
switching configs, creating a new launch configuration, modify the configuration, delete a configuration, switching between different projects, project close and reopen and eclipse restarting, switching workspaces. 
Expected result: Indexer …

IEP-479: Fixed indexer fails issue on change configuration

---

README.md
README_CN.md

This PR:
1. Fixed the issue switching from EN and CN readme files;
2. Added link for switching language section.

Fix invalid links in readme files (IEP-488)

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESPToolChainProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java

The default option for gdb executable in the GDB setup client is now based on IDF_TARGET

IEP-490: Provided right gdb executable to gdb client

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfigurationProvider.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizard.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/EclipseUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/LaunchBarListener.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/messages.properties

Functionality with the update method was moved to the LaunchBarListener, that's triggering immediately after we are changing the target to the target with a different IDF_TARGET value. Functionality is a little bit refactored, so it's working with debug mode also. 
Test cases:
1.  Create and build the project > change target > "IDF TARGET CHANGED" message appears > click Yes > project is cleaned and the next build is working.
2. Create and build the project > change target > "IDF TARGET CHANGED" message appears > click No > Indexer fails due to the incorrect target 
3. Select some project > create a new launch target > "IDF TARGET CHANGED" message appears if the new launch target is different from one in the build folder configuration
4. Repeat test cases 1,2 and 3 on the debug …

IEP-498 Indexer fails on changing the launch target

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/IDFDebugLaunchDescriptorType.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/core/IDFCoreLaunchConfigProvider.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/core/IDFLaunchDescriptorType.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/LaunchBarListener.java

this PR includes fixes for both problems: incorrect updating launch configuration dropdown box and losing target for duplicate configuration because of it. Also, small fixes were added to avoid NPE.
Test cases:
1. Create a new project > create a few debug and launch configurations for this project > close the project > dropdown box will remove all configuration related to this project > open the project again > all configurations are added back to the dropdown box
2. Create a new project > create a few debug and launch configurations for this project > close the project > dropdown box will remove all configuration related to this project > restart eclipse > all configuration related to the closed project are still removed > open the project again > all configurations are added back to the …

IEP-442: Correct updating launch configuration dropdown box

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizard.java

We need to call `manager.addLaunchTarget(typeId, id);` every time, when we are editing esp IDF target. This allows us to trigger the launch bar listener and show the "IDF launch target changed" message when it's needed. It's also allows us to not duplicate code, that is using in launch bar listener.
By calling `manager.addLaunchTarget(typeId, id);` we are not adding target if it already exists in related hashmap, so it's safe to call it every time when we are editing esp idf target.

IEP-524: IDF launch target changed message is not showing

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java

test cases:
1. create a target with some name like "espTest" -> open launch configuration -> flash over jtag -> in the target section as the default option the correct target is selected. 
2. same test on the debug configuration

IEP-523: Providing the idf target attribute instead of the target name

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/Configuration.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ConfigurationAttributes.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/Messages.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabStartup.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/messages.properties

The OpenOCD Options composite has been added to the Startup tab with the "Flash every time with application binaries option". We can add more options in the future there, for example "OpenOCD log" with the command -d3 -l oocd.log.
Also, as part of the PR, scrollbars have been added to the Debugger and Startup tabs.

IEP-553 GH #385: Need option for not download the program before debugging.

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/META-INF/MANIFEST.MF

Here is the problem:
mentioning a specific version for LaunchBar plugin is causing this issue.

IEP-574: Fix for update site installation on Eclipse 4.19

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/ExportIDFTools.java

We are having `python dependencies are not satisfied` issue with the Bosch customer. This has happened because they are having multiple versions of python versions installed and CMake build is picking up the python version from the system instead of python from the CDT build PATH.
Let's rely only on `idf.py export` command `PATH` output for building idf projects. That is having all the required paths and also don't see a need to append to the existing path. That basically avoids configuring multiple tool chains on the path environment also.

IEP-562 Fix: Avoid appending to existing PATH env variable in CDT build

---

bundles/com.espressif.idf.sdk.config.core/src/com/espressif/idf/sdk/config/core/KConfigMenuItem.java
bundles/com.espressif.idf.sdk.config.core/src/com/espressif/idf/sdk/config/core/KConfigMenuProcessor.java
bundles/com.espressif.idf.sdk.config.ui/src/com/espressif/idf/sdk/config/ui/ConfigContentProvider.java
bundles/com.espressif.idf.sdk.config.ui/src/com/espressif/idf/sdk/config/ui/SDKConfigurationEditor.java

PR summary:
- rendering menuconfig elements as bool type, so the user is able to enable/disable them
- by enabling/disabling menuconfig elements, corresponding menus will be added/removed in the treeview. 
- highlighting menuconfig elements by adding the icon.
before:
menuconfig element is missing, no way to enable/disable it 
after:
disabled menuconfig
enabled menuconfig

IEP-486: GH #315: SDK Configuration editor do not recognize Kconfig "menuconfig ...." line and it parameters.

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/ExecutableFinder.java

The class `ExecutableFinder` was returning the match in find method for only the first path and if found it was okay if not it was null which it was for majority cases. Fixed that by adding null check and continuing the loop till it finds the path.

IEP-584: Logic fixed in finding the path from the system path

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeConstants.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeDataManager.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeDetailsComposite.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeOverviewComposite.java

Application Size Analysis is now working with all versions of the esp-idf.
Tested on Esp-idf 4.2, 4.3, 4.4 and 5.0. Windows10 and macOS. 
also works with different targets:
esp32 -
esp32c3 with single diram column:
for ESP-IDF 4.4 and higher, in the details, columns Other and Total have been changed to Ram Total and Flash Total accordingly

IEP-540 Not opening Aplication Size Analysis on esp-idf 4.4 and higher

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java

Now we are changing CMakeLists.txt when the project is renamed or added. That allows generating binaries with the same name as the project

IEP-597: Binaries name according to the project name

---

bundles/com.espressif.idf.launch.serial.core/META-INF/MANIFEST.MF
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java

The "Serial port not found" error does not occur when the user selects "flash over jtag" in the launch configuration.
But I decided to edit this error message anyway to make it more user-friendly. Instead of showing an error, we now guide the user to edit their launch target, where they can select a serial port.
How to reproduce:
1. Create the launch target without selecting the serial port
2. Flash the project over UART
3. You will see confirm dialog, click OK
4. Now you will see the "Edit launch target" dialog, where you can select the Serial Port

IEP-542 Serial port was not found error while JTAG flashing

---

bundles/com.espressif.idf.core/META-INF/MANIFEST.MF
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/Messages.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/messages.properties
bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/OpenDialogListenerSupport.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/DataSizeUtil.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/MessageLinkDialog.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/Messages.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/ParitionSizeHandler.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/messages.properties
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/MessageLinkDialog.java

Now, after the build, we can see the application's RAM and flash usage using the idf_size.py command:
If the remaining app size is less than 30%, we will show the warning message with the link to the [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html?highlight=partitions%20csv#creating-custom-tables)

IEP-525 Show Application RAM and flash usage info after the build

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java

On the latest eclipse with the latest CDT, "flash over Jtag" checkbox in the launch configuration is not visible
Eclipse Version: 4.22.0.v20211124-1800
Eclipse CDT Version: 10.5.0.202109270023
To fix this, I had to move this checkbox to the main composite

IEP-616: Flash over JTAG checkbox is not visible with the latest eclipse and cdt

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFVersionsReader.java

Based on the https://github.com/espressif/esp-idf/tags. Tags could contain patterns like `-dev`, `-beta`, `-rc1`. So we are replacing `-.*` regex pattern with 0 to check if the version is higher than 4.0.0

IEP-621 ESP-IDF version check breaks IDF download page

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/install/IDFDownloadPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/install/messages.properties

Removing `requirements.txt` additional validation check as part of the esp-idf folder validation. Will rely on `/<esp-idf folder>/tools/idf.py` file check to validate whether it's an esp-idf directory or not.
Will keep this for v2.4.1 release

Fix: Removing requirements.txt validation check

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabStartup.java

The problem occurs in an older version of openocd, which does not support flashing jtag. Fixed by adding null checking

can not create launch configuration ESP-IDF GDB OpenOCD Debugging (IEP-630)

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESPToolChainManager.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

added: removing previously installed toolchains after installing new tools.
before changes:
after changes:

IEP-636: Two versions of the toolchain for each target after installing the new esp-idf and tools.

---

bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/connector/SerialPortHandler.java

sometimes socket server starts after the SocketServerHandler.getServerPort(), because the Socket server starts in a different thread. These changes are forcing to start socket server first

Opening a terminal for the first time after Eclipse starts hangs at "Connecting..." and throws an NPE (IEP-637)

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java

modified openocd executable for mac and linux to check version

IEP-641: Openocd version check not working on linux and mac

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/ParitionSizeHandler.java

Made code for checking the remaining size more robust. Works if the binary name and project name do not match and if a binary file is missing

Version 2.4.1 (Eclipse) and 2.4.0 (Espressif IDE): Build fail after image is build for working project without clear reason. (IEP-647)

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/EclipseIniUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/menuitem/LanguageDynamicMenuItem.java

Original issue: Unable to change a language when the root folder name is not eclipse
Fixed
The issue was we were using constant name eclipse while getting install location which was failing as the RCP is now named espressif-ide
We are now using the system property to fetch the name of the launcher and appending that to the path which resolves the error.
Tested on Windows need testing on MAC and LINUX

IEP-634: Bug fix for Language Change

---

bundles/com.espressif.idf.serial.monitor/src/com/espressif/idf/serial/monitor/SerialMonitorBundle.java
bundles/com.espressif.idf.serial.monitor/src/com/espressif/idf/serial/monitor/core/LocalTerminal.java
bundles/com.espressif.idf.ui/META-INF/MANIFEST.MF
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/EspresssifPreferencesPage.java
tests/com.espressif.idf.ui.test/.gitignore

Changed the preference store, to get SERIAL_MONITOR_NUMBER_OF_CHARS_IN_LINE and SERIAL_MONITOR_NUMBER_OF_LINES variables from the espressif preference page. If these changes are ok, we can remove the initializeDefaultPreferences method, since looks like we don't use it anywhere else

Espressif preferences for the serial monitor has no effect on it

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/installcomponents/handler/InstallCommandHandler.java

The initial code was not catering for the download of sources and headers for the components. We just need to specify the IDF_COMPONENT_MANAGER variable in the environment and the CMake build system will take care of the rest.
Sources for this change are the documentation from
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-component-manager.html
Also updated the code to use the Eclipse Jobs API to avoid the UI getting stuck on the install operation

IEP-671: ESP-IDF Install Components not fetching the components sources for installed components.

---

bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/util/ESPFlashUtil.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java

Now, in the `arguments` line for launch configuration we have the variable "${serial_port}", which will be replaced with the actual serial port, that is selected in the launch target.

IEP-670 GH #509: Switching to different Serial Port in the ESP Target selector does not take effect

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/LaunchBarListener.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/UIPlugin.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/messages.properties

Added a message, when a selected target doesn't match the target, which is selected for the jtag flashing. It will navigate the user to configuration options, where it's possible to change the selected target and a board for the jtag flashing
Test cases:
1. For the launch configuration, select the "Flash over JTAG" option and choose some board with an esp32 chip and click OK. Then select new target esp32s2. After this, you will be able to see this message. Click "Yes" and you should be navigated to the launch target options, where it's necessary to select a new board.
2. Same as 1 test case, but for debug configuration
3. Unselect "Flash over JTAG" option from the launch configuration. In this case, after selecting a target, you should not see same message, but if project is built, you …

IEP-679: Auto change the launch target after clicking on the launch configuration

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/menuitem/LanguageDynamicMenuItem.java

Changed to system property **eclipse.launcher** for restarting eclipse.

IEP-692: Fix to restart eclipse for different platforms

---

.github/workflows/ci.yml
releng/com.espressif.idf.configuration/pom.xml

With this PR we are enabling spotbugs code quality checker as part of the PRs. I think we should start looking into these bugs and fix some high-priority issues.
However, the build fail on error is set to false for now. We could set to true in the future and enforce every PR to fix newly reported issues.

IEP-426:Add findbugs to reporting

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/RecheckConfigsHelper.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/CMakeBuildTab2.java

Briefly about the issue. Sometimes launch configurations are bugged for some reason, so it's impossible to edit them because of the NPE in process of getting the build configuration. As figured out, the problem is similar to the old problem with "Build not configured correctly", which we fixed a long time ago. 
The fix for that issue is to recheck configs and put any of the ESP toolchains to the settings, so it will be possible to create an IDF build configuration. Since we already have code for these purposes, this PR is mainly about refactoring and using the same code in different places.

IEP-687 Random NPE when opening the launch configuration options

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFEnvironmentVariables.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

This will avoid build errors when components are added but the component manager is not enabled

Fix: Enable IDF_COMPONENT_MANAGER by default

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java

We need to save the launch target attribute for the configuration each time we edit it. Otherwise, it may cause the value ​​from the configuration to get out of sync with a value from the launch target bar.
We are already doing it for launch configuration, so this PR contains changes for debug configurations only.

IEP-703: Saving a target attribute for a config each time when editing.

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

Apply a single quote for the string when the string has arbitrary chars. It is essentially to fix the below message.
```
!ENTRY com.espressif.idf.core 1 0 2022-06-07 21:15:07.400
!MESSAGE esp-idf.json file doesnt exist at this location: {0}
```

Fix: single quote for messageformat when string has arbitrary chars

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java

Previously append was removing slash from the path. 
```
Users/kondal/esp/esp-idf-v4.4.1/components/esptool_py/esptool
```
As you could see there was no slash in the front of the path hence esptool.py was not accessible from the terminal. This got fixed now.
**How to verify:**
1. Go to the ESP-IDF terminal
2. type esptoo.py

ESP-IDF Terminal: esptool.py is not accessible in terminal

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

Installing WebSocket into the python environment instead of the global python directory.
Fixes # ([IEP-722](https://jira.espressif.com:8443/browse/IEP-722))
- Clean the esp-idf python environment in the` .espressif` folder. 
- Restore eclipse env variables: Preferences -> C/C++ -> Build -> Environment - Restore Defautls
- Install Tools from the Eclipse
- Check the install tools log. Below setting `IDF_PYTHON_ENV_PATH` should be executing installing websocket command `Executing /Users/denysalmazov/.espressif/python_env/idf5.0_py3.9_env/bin/python -m pip install websocket-client`
- Try to launch [the Serial Monitor](https://github.com/espressif/idf-eclipse-plugin#viewing-serial-output) to check if it works ok.
* …

IEP-722: Use python (not pip) for installing websocket client

---

bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/SerialFlashLaunchTargetProvider.java

Added esp32s3 and esp32c3 to the default launch target list on the eclipse toolbar
Fixes # ([IEP-721](https://jira.espressif.com:8443/browse/IEP-721))
1. Launch Espressif-IDE
2. Verify the default launch target list on the eclipse toolbar, it should show esp32c3 and esp32s3 in the list. 
* ESP-IDF Version: master
* Espressif-IDE version: Current PR build

IEP-721: Add esp32c3 and esp32s3 to the launch target list

---

bundles/com.espressif.idf.branding/plugin.xml
bundles/com.espressif.idf.branding/plugin_customization.ini
releng/com.espressif.idf.product/idf.product
releng/com.espressif.idf.product/plugin_customization.ini

Added progress monitor along with the text on the espressif-ide splash screen
Fixes # ([IEP-731](https://jira.espressif.com:8443/browse/IEP-731))
1. Download espressif-ide from this PR
2. Verify if you are able to see the progress monitor and text message on the splash screen
* ESP-IDF Version: master
* Espressif-IDE version: Current PR build
- Splash screen

Add splashscreen progress monitor

---

tests/com.espressif.idf.ui.test/src/com/espressif/idf/ui/test/executable/cases/project/NewEspressifIDFProjectTest.java

This was cherry picked for quick merge to the master from IEP-448
Fixes # ([IEP-738](https://jira.espressif.com:8443/browse/IEP-738))
Tested on ([IEP-448 PR](https://github.com/espressif/idf-eclipse-plugin/pull/419)) builds
* Github Runner Ubuntu
Master and all subranches should be rebased again for successful test runs.

IEP-738: select esp32s2 target for DFU test

---

.github/workflows/ci.yml
releng/com.espressif.idf.product/pom.xml
releng/ide-dmg-builder/create-dmg/create-dmg
releng/ide-dmg-builder/ide-dmg-builder-aarch64.sh

1. Changed macOS x86_64 Espressif-IDE.dmg to `Espressif-IDE-macosx-cocoa-x86_64.dmg`
2. Added new arm64 dmg build `espressif-ide-macosx.cocoa.aarch64.dmg`
3. Entitlements added to arm64 dmg
4. Verified espressif-ide-macosx.cocoa.aarch64.dmg on Apple M1, we are able to launch it successfully after fixing the Entitlements issue
Fixes # ([IEP-731](https://jira.espressif.com:8443/browse/IEP-731))
Need to verify whether espressif-ide is working on the Apple M1 - Launch espressif-ide, install tools, build, flash, serial monitor, and debugging
* ESP-IDF Version: master
* Espressif-IDE version: Current PR build
* OS: Apple M1
- Espressif-IDE
- Build
- Flash
- Serial Monitor
- Debugging

Espressif-IDE arm64 build

---

.github/workflows/ci.yml

CI builds were failing because of the accessibility bug in Linux will cherry pick the changes from my branch in [IEP-448](https://jira.espressif.com:8443/browse/IEP-448) that seems to be fixing the issues
Fixes # ([IEP-743](https://jira.espressif.com:8443/browse/IEP-743))

IEP-743: Fixed the CI Build Issues

---

bundles/com.espressif.idf.branding/META-INF/MANIFEST.MF
bundles/com.espressif.idf.branding/pom.xml
features/com.espressif.idf.feature/feature.xml
features/com.espressif.idf.feature/pom.xml
releng/com.espressif.idf.product/idf.product
releng/com.espressif.idf.product/pom.xml
releng/com.espressif.idf.update/pom.xml

Bumped version to v2.6.0
- Release change
Verify generated artifacts version numbers this include espressif-ide, update site
* ESP-IDF Version: NA
* OS (Windows,Linux and macOS): NA
- Update site
- Installation

Bump version to v2.6.0

---

.github/workflows/nightly.yml
.github/workflows/upload.yml

This will push the Espressif IDE update artifacts to the s3 bucket. 
Nightly update site https://dl.espressif.com/dl/idf-eclipse-plugin/updates/nightly/
Fixes # ([IEP-481](https://jira.espressif.com:8443/browse/IEP-481))
Case 1:
- Launch Espressif-IDE
- Add nightly update site https://dl.espressif.com/dl/idf-eclipse-plugin/updates/nightly/
- Eclipse should be able to get the nightly changes from the master branch
* ESP-IDF: NA
- Update

IEP-481: Push Nightly master builds to amazon s3

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFCorePreferenceConstants.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/EspresssifPreferencesPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/messages.properties

CCache enable/disable control from the preferences page 
Fixes # ([IEP-736](https://jira.espressif.com:8443/browse/IEP-736))
Case 1:
- Launch Espressif-IDE
- Build a Hello-world project 
- By default project should build CCache enabled (look for -DCCACHE_ENABLE=1 in the console)
Case 2:
- Launch Espressif-IDE
- Go to Espressif preferences and disable CCache
- Build a Hello-world project 
- Project should build with CCache disabled (look for -DCCACHE_ENABLE and it shouldn't be found)
* ESP-IDF Version:master
- Build
- Espressif Preferences page

IEP-736: CCache enable/disable control from preferences page

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFCorePlugin.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/ExportIDFTools.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

- Updated and refactored code to return status from commands execution method.
- Added a job change listener to look for error status from job
- Added the ability to revert back to old env vars incase of failures
Existing flows and with errors are working fine but it still needs to be tested on Linux and Mac

IEP-720: Fix for python script errors

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/dsf/LaunchConfigurationDelegate.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/Messages.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/messages.properties

Provide simple error messages based on the error code without specifying the name of the dll that is missing. This fix is ​​specific to Windows OS.
Fixes # ([IEP-635](https://jira.espressif.com:8443/browse/IEP-635))
Case 1:
- To make GDB crash you need to remove libgcc_s_seh-1.dll from the toolchain.
```
C:\projects\esp-idf>where libgcc_s_seh-1.dll
C:\Users\alexey\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin\libgcc_s_seh-1.dll
C:\Users\alexey\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s2-elf\bin\libgcc_s_seh-1.dll
C:\Users\alexey\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32s3-elf\bin\libgcc_s_seh-1.dll …
```

IEP-635 Provide diagnostic info on why GDB is crashed

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

To enable function definition navigation in the Eclipse IDE, as part of v2.5.0 we have added `esp_idf_components` to the root of the project. Based on the user's feedback we are moving this to the `/build/ide/esp_idf_components` to maintain sanity at the project level
Fixes # ([IEP-648](https://jira.espressif.com:8443/browse/IEP-648))
Case 1:
- Launch Espressif-IDE
- Build a Hello-world project 
- After the build, `esp_idf_components` folder should be created in the `/project/build/ide/ folder`
-  And, there shouldn't be any errors in the project source files and the user should be able to navigate the source code definition.
* ESP-IDF Version:master
- Build
- Indexing …

IEP-648: moving esp_idf_components to build folder

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFEnvironmentVariables.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFVersionsReader.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/Version.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/EclipseIniUtil.java
bundles/com.espressif.idf.sdk.config.ui/src/com/espressif/idf/sdk/config/ui/SDKConfigurationEditor.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/IDFConsole.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tracing/AppLvlTracingDialog.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/ExportIDFTools.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

The idea is to give user the visual feedback on the console when installing the tools. Currently all the installation was shown in the plain default color but now we are showing the error messages in the red color.
Fixes # ([IEP-681](https://jira.espressif.com:8443/browse/IEP-681))
The scripts in the esp-idf directory install_tools.py can be edited to remove or add some lines that can cause the script to fail. This should then return an exception to the process runner which will lead to the status to be error. From there we can capture the exception message and show that error message in red color on the console.
* OS (Windows,Linux and …

IEP-681: Show Tools installation error messages in red color

---

.github/workflows/ci.yml

Fix for eclipse launch parameter for CI Issues
_**-vmargs -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8989**_
Fixes # ([IEP-744](https://jira.espressif.com:8443/browse/IEP-744))
Running builds on self hosted runner.

IEP-744: Fix for eclipse launch parameter for CI Issues

---

FAQ.md

Configure esp-who in espressif-ide
Added documentation on how to configure esp-who in espressif-ide

IEP-765:Configure esp-who in espressif-ide

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFEnvironmentVariables.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeDataManager.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java
releng/com.espressif.idf.target/com.espressif.idf.target.target
releng/com.espressif.idf.update/category.xml

Unable to install IDF eclipse plugin on Eclipse 2022-09 CDT due to the following reasons:
1. Latest Eclipse CDT is missing with the org.apache.batik.xml plugin
2. Old embedded CDT plugins have become invalid with the latest CDT
What did we do?
1. Added org.apache.xml.batik  to the idf update site plugins update
2. Updated swtcharts from 0.12.0 to 0.1.3.0
3. Updated embedded CDT core plugins to the latest
4. Removed unwanted embedded plugins from the target definition
Fixes # ([IEP-768](https://jira.espressif.com:8443/browse/IEP-768))
Test:1
- Install Eclipse CDT 2022-09
- Install PR using the update site 
Test:2
- Install Embedded CDT 2022-09
- Install PR using the update site 
Test:3
- Install Espressif-IDE v2.6.0
- Install PR using …

Eclipse 2022-09 support

---

bundles/com.espressif.idf.core/plugin.xml
bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFEnvironmentVariables.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32C2CMakeToolChainProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32C2ToolChain.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32CMakeToolChainProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32ClangCmakeToolChainProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32ClangToolChain.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32H2CMakeToolChainProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32H2ToolChain.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESP32ToolChain.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESPToolChainManager.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESPToolChainProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfigurationProvider.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/SerialFlashLaunchTargetProvider.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

Added esp32-c2 and esp32-h2 targets, which are using the same riscv toolchain as the esp32-c3 target, so it's safe to add these targets with older version esp-idf as well. 
Also, the bug fix related to changing the toolchain to the xtensa-clang was added to this PR
New feature # ([IEP-756](https://jira.espressif.com:8443/browse/IEP-756))
Test 1:
- install tools from IDE
- check existing toolchains. `Eclipse -> Preferences -> C/C++ -> Core Build Toolchains`. There should be all toolchains including esp32-c2 and esp32-h2. Xtensa-clang toolchain has a clang type 
- select esp32-c2 or esp32-h2 and build a project with it. Check if a building is ok.
Test 2:
- select esp32 target
- …

IEP-729: ESP32-C2 and ESP32-H2 support in IDEs

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESPToolChainManager.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/SerialFlashLaunchTargetProvider.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizardPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsInstallationHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java
tests/com.espressif.idf.ui.test/resources/default-files/NewProjectTest/main/.project

Removed duplicate targets from a target list. Refactored code related to getting targets from the toolchains list.
Note: If you downgrade esp-idf, you will still see new targets such as esp32c2 or esp32h2 in the target list bar. For now, we agreed to keep them, so users will be able to change esp-idf versions dynamically without losing saved launch targets.
Fixes # ([IEP-790](https://jira.espressif.com:8443/browse/IEP-790))
Test 1:
- Install some old esp-idf version (4.1 for example)
- When editing or creating new target, in combo will be only available targets based on existing toolchains:
Test 2:
- Install some new esp-idf version (master for example)
- When editing or creating new target, in combo will be only available targets based …

IEP-790: remove duplicate targets from target lists

---

releng/com.espressif.idf.target/com.espressif.idf.target.target
releng/com.espressif.idf.update/category.xml

Unable to install 2.7.0 nightly on eclipse 2022-09 CDT due to missing dependencies
Fixes # ([IEP-805](https://jira.espressif.com:8443/browse/IEP-805))
- Download and install 2022-09 Eclipse CDT
- Install the latest 2.7.0 nightly - this will fail
- Try with PR build and the update should go through without any issues
These steps should be repeated for Espressif-IDE 2.6.0 and Embedded CDT 2022-09 and 06 versions
- Update site installation

IEP-805: fix for Unable to install 2.7.0 nightly on eclipse 2022-09 CDT due to missing dependencies

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/LaunchBarListener.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/messages.properties

Fixes # ([IEP-817](https://jira.espressif.com:8443/browse/IEP-817))
Test 1:
- Build project with esp32 target, after build, change the target for something else.
Test 2:
- Edit the launch configuration and select Flashing via jtag  or create a debug configuration -> select esp32 board. Close the dialog and change the target via target bar.
- Launch bar listener

IEP-817: More informative notification on target change

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeDataManager.java

`idf_size <map_file> --format json` instead of `--json` was added in the 5.1 version, not 5.0 as was thought previously. This caused the application size analysis to crash
Fixes # ([IEP-816](https://jira.espressif.com:8443/browse/IEP-816))
Test 1:
- install tools with esp-idf 5.0 -> create project -> build -> open application size analysis 
Test 2: 
- install tools with esp-idf higher or lower than 5.0 -> create project -> build -> open application size analysis. 
- Application Size analysis editor

IEP-816: GH #640: Not opening Aplication Size Analysis on esp-idf 5.0

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

Updating the default value for openocd path immediately after tools installation.
Fixes # ([IEP-815](https://jira.espressif.com:8443/browse/IEP-815))
Test 1: 
- Make sure, that openocd can be updated (the latest version is not yet installed). To do it: 
Go to Preferences -> Espressif -> Global OpenOCD Path
- Now install tools from the latest esp-idf master. After the installation the Global OpenOCD Path should be updated:
Test 2: 
- Create a debug configuration and check if Actual executable value is updated accordingly. 
- Espressif Preference Page 
- Debugger Tab

IEP-815: openocd path in the Espressif preferences page requires the eclipse restart to update a value

---

releng/com.espressif.idf.target/com.espressif.idf.target.target

CI Build fix: Tag IEP builds with Eclipse 2022-09 target
Fixes # ([IEP-838](https://jira.espressif.com:8443/browse/IEP-838))
Build has to go through and should be able to install the update site generated with espressif-ide v2.7.0
- Update site

CI Build fix: Tag IEP builds with Eclipse 2022-09 target

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/MessageLinkDialog.java

com.espressif.idf.core.prefs file was not persisted after restarting Eclipse. Added flashing the preferences to save the file
Fixes # ([IEP-807](https://jira.espressif.com:8443/browse/IEP-807))
- Test A

GH #629: Low application partition size turn off notification

---

bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/connector/SerialPortHandler.java

Fix error for Illegal Thread State exception causing monitor issues
The thread for handling the socket server messages gave IllegalThreadState exception as while flashing the thread was already running and after resume call for the serial port handler the exception was thrown which caused the processes to become orphan and they were showing themselves detach from the eclipse but were running in the background holding the serial port.
Just needed to add a check to see if the thread was alive or not.
Fixes # ([IEP-814](https://jira.espressif.com:8443/browse/IEP-814))
- Flash a project with the monitor running and connected to that project, after flashing the monitor should resume automatically …

IEP-814: Fix error for Illegal Thread State exception causing monitor issues

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfigurationProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/RecheckConfigsHelper.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/SerialFlashLaunchConfigTabGroup.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/CMakeBuildTab2.java

As changes are relevant to the both tickets, this PR contains fixes for: 
- IEP-840: Build settings not getting saved to specific launch configuration 
- IEP-841: Add the Build Settings tab in the Launch configuration creation dialog
Explanation to the code changes: 
- In order to save and use build settings for each individual project launch configuration, we must avoid using the default build configuration, which is the same for all launch configurations. Instead, we need to create build configurations based on the launch configuration name or the project name as the default option.
- In addition, to avoid problems with a misconfigured build, we must ensure that the selected toolchain is extends from AbsractESPToolChain
- In order to be able to provide a Build Settings tab during the …

IEP-840 & IEP-841: Fix for Build settings save and add build settings tab in new launch config

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/Messages.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/messages.properties
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

Changes to handle the change in idf in esp_idf.json config file
Fixes # ([IEP-701](https://jira.espressif.com:8443/browse/IEP-701))
- Bug fix (can be a breaking change)
To test we need to have this tested with installer or some existing espressif ide installation.
- Need to change the idf path in config file
- It should work fine without any changes
- First initialization should be okay
* 
(@AndriiFilippov)
Use the esp_idf.json file usually found when installing the ide via installer. Try running the IDE and then changing version and IDF_PATH in the json configuration file that's what the installer is doing when used again just to change the version. You should get a …

IEP-701: Changes to handle the change in idf in esp_idf.json config file

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java

Most changes to the code are related to applying code formatting. The main changes, which includes the bug fixe is next:
- in setDefaults() method we are using defaultString = null; instead saved value from previous configurations. Then we are initializing fields like this: `fGdbServerOtherOptions.setText(configuration.getAttribute(ConfigurationAttributes.GDB_SERVER_OTHER,
fGdbServerOtherOptions.getText()));`
fGdbServerOtherOptions is not null and not empty, because we are updating it in the initialization phase with the default option. 
Fixes # ([IEP-853](https://jira.espressif.com:8443/browse/IEP-853))
Test 1:
- Create a new project -> select target esp32s2 -> create a debug configuration for this project -> check if `Config options` …

IEP-853: The default debug config command doesn't match the selected target

---

bundles/com.espressif.idf.serial.monitor/src/com/espressif/idf/serial/monitor/core/IDFMonitor.java
bundles/com.espressif.idf.serial.monitor/src/com/espressif/idf/serial/monitor/handlers/SerialMonitorHandler.java
bundles/com.espressif.idf.ui/META-INF/MANIFEST.MF
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

Verify and install websocket before launching idf monitor.
As we have added webscocket plugin dependency with the core dump debugging it was considered as a regression for customers as it's failed after update. 
Fixes # ([IEP-852](https://jira.espressif.com:8443/browse/IEP-852))
Remove the websocket dependency from the command line using the **_pyhton -m pip uninstall websocket_** using the python from the ESP after installing tools in IDE.
Run and Build any sample project and launch serial monitor. The serial monitor should work now as it checks and installs the dependency or will fail with an exception logged in file stating missing dependencies. …

IEP-852: Check for websocket dependency before starting serial monitor

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/plugin.xml
bundles/com.espressif.idf.debug.gdbjtag.openocd/preferences.ini
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/OpenOCDPluginStartup.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/preferences/DefaultPreferenceInitializer.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/preferences/DefaultPreferences.java

The [default timeout limit ](https://sourceware.org/gdb/onlinedocs/gdb/Remote-Configuration.html)to wait for the remote target to respond is 2 seconds else GDB Client will be thrown an exception to the user.
As per the client reports, this seems to be a problem where they have to increase the timeout to 20 seconds to make it work.
Fixes # ([IEP-831](https://jira.espressif.com:8443/browse/IEP-831))
Test 1:
1. Create a new workspace 
2. Create a new debug configuration and navigate to the Debugger tab
3. See if you're able to see a new command option in the GDB client with "set remotetimeout 20"
4. Make sure debugging is working
Test 2:
1. Go to your existing workspace
2. Create a new debug configuration and navigate to the Debugger tab …

IEP-831: Set remotetimeout to 20 sec for GDB Client

---

README.md

Documentation ToC restructure
Check this
https://github.com/espressif/idf-eclipse-plugin/blob/7e6a29493fd8d6303d3f6b86d0d28649106f924d/README.md
Why?
* Simplified ToC Structure
* Separating basic workflows from the advanced features that IDE offers
* Avoid confusion to the users - for example, we have two Install Tools options so keeping them together might confuse the user.
Check this
https://github.com/espressif/idf-eclipse-plugin/blob/7e6a29493fd8d6303d3f6b86d0d28649106f924d/README.md

Documentation ToC restructure

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/ProjectCleanCommandHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/ProjectFullCleanCommandHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/PythonCleanCommandHandler.java

passed the build folder path `-B folder_path` to the clean commands to support the custom build folder
Fixes # ([IEP-864](https://jira.espressif.com:8443/browse/IEP-864))
Test 1:
- Create a new project
- Build
- Try clean commands on it (Project clean, FullClean and Python clean)
Test 2:
- Repeat test 2, but on the custom build folder
- Clean commands
- Custom build folder

IEP-864 Clean commands do not work with custom build directories

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/EclipseIniUtil.java

The default launcher name is upper case where as the file for properties is found to be always in the lower case. This cause issues in UNIX and LINUX based OS.
Simply changed the code to convert the launcher name property to lowercase regardless of OS because windows is case insensitive and UNIX and LINUX are not and this was probably only tested on Windows when the feature was created making it appear much later. 
Fixes # ([IEP-865](https://jira.espressif.com:8443/browse/IEP-865))
Change the language in the Espressif IDE to Chinese. Repeat this test on all platforms
* ESP-IDF Version: Doesn't matter

IEP-865: Error changing language due to case invalidation in file name

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java

Some python versions can be added to registry "3.7-32" so it causes java.lang.NumberFormatException:
Fixes # ([IEP-867](https://jira.espressif.com:8443/browse/IEP-867))
Test 1:
- install tools, and check installed tools with different python versions. 
- Install Tools command
- List installed tools command

IEP-867 The number format exception for some python versions

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java

We used the same default gdb client executable for all configurations. This was causing incorrect defaults for new projects. 
Instead of providing a default value from the persistence preference, we are getting the default value based on the selected target, or providing the saved value after the debug configuration is already created
Fixes # ([IEP-869](https://jira.espressif.com:8443/browse/IEP-869))
Test 1:
- create a new project
- select some target 
- create a new debug configuration for this project
- the default target and the default gdb client executable must be correct
Test 2:
- repeat test 1, but with a different target
Test 3:
- try to run a debug
* ESP-IDF …

IEP-869: Default gdb client path is wrong for the new project

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsInstallationHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

Tools installation wizard was not exporting openocd path in configurations.
Fixes # ([IEP-868](https://jira.espressif.com:8443/browse/IEP-868))
Tested on windows by installing tools through wizard and then verifying variable in preferences
Espressif > OpenOCD Path.
Needs to be tested on other platforms.
* ESP-IDF Version: shouldn't matter

IEP-868: Fixing the export of global openocd path in preferences

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java

Fixes # ([IEP-870](https://jira.espressif.com:8443/browse/IEP-870))
Test 1:
- in the debug configuration select esp32c2 target -> select esp32c2 board
- Debug configuration

IEP-870: Missing gdb executable for esp32c2 target

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java

Fix the "Restore defaults" button in the Debugger Tab. The defaults values are:
esp32 target, default flash voltage, the xtensa toolchain, config options according to the esp32 target and board 
Fixes # ([IEP-873](https://jira.espressif.com:8443/browse/IEP-873))
Test 1
- Create a new debug configuration
- Manually change the values in the fields all over the Debugger tab
- click Restore Defaults, and make sure everything is reset to the default
- Debugger Tab

IEP-873: Fix the "Restore defaults" button in the Debugger Tab

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/ToolChainUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsInstallationHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

we are configuring toolchains in three different places: install tools, install tools wizard, and initialiazeToolsStartup class (for the offline installer). PR contains the refactoring - moving the same methods to a separate class which also adds the necessary line to the initializeToolsStartup class, which fixes the problem. 
Fixes # ([IEP-879](https://jira.espressif.com:8443/browse/IEP-879))
Test 1:
- clear workspace, install tools -> Launch bar should contain launch targets after tools installation
Test 2:
- repeat Test 1 but install tools with the Tools Installation wizard
Test 3:
- after installing the Espressif IDE by the offline installer, the launch target bar should be initialized …

IEP-879 Offline installer release 2.8.1 - after installation the "Launch Target Bar" is empty.

---

bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/controls/SerialSettingsPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/EclipseUtil.java

As reported here https://github.com/espressif/idf-eclipse-plugin/issues/697 
Fix: Filter non-IDF projects from the ESP-IDF Serial Monitor
Fixes # ([IEP-877](https://jira.espressif.com:8443/browse/IEP-877))
1. Create IDF project 
2. Create a non-IDF project - a simple c/C++ project
3. Open ESP-IDF Serial Monitor dialog
4. There shouldn't be any non-idf projects listed
* OS (Windows,Linux and macOS): Tested in macOS
- ESP-IDF Serial Monitor

Fix: Filter non IDF projects from the ESP-IDF Serial monitor

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ESPToolChainManager.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsInstallationHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsJsonParser.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsUtility.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/wizard/pages/ManageToolsInstallationWizardPage.java
releng/com.espressif.idf.target/com.espressif.idf.target.target

There were some issues in tools installation wizard particularly on Mac os due to some java functions not working because of limited permissions there while extraction of the files from a gz archive
Fixes # ([IEP-825](https://jira.espressif.com:8443/browse/IEP-825))
This change requires that tools installation wizard to be tested on Mac os and after that we need to verify this on other platforms as well. If any issues found for those they will be taken in their respective tickets 
* ESP-IDF Version: **All**
* OS (Windows,Linux and macOS): **All**

IEP-825: Fixing issues with tools installation wizard on MAC OS

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/wizard/pages/InstallEspIdfPage.java

Some SWT Flags are not supported on Linux because of issues with Gtk.
Removed all the unsupported flags for the SWT based on the information on official swt faq
https://www.eclipse.org/swt/faq.php#gtkwidgethidden
Fixes # ([IEP-887](https://jira.espressif.com:8443/browse/IEP-887))
Use the steps to reproduce and verify that controls are now rendered properly
Espressif -> Download and Configure ESP-IDF -> Select any esp-idf folder -> pop-up window ask to install tools -> click "NO"  -> go to "Espressif -> ESP_IDF Tools Manager -> Tools Installation Wizard -> click "Next" -> see UI issue -> click "Next" -> click "Back" -> see again UI issue.
* ESP-IDF Version: All
* OS …

IEP-887: UI Collisions and unusable controls on Linux for Tools Installation Wizard

---

bundles/com.espressif.idf.ui/plugin.xml

Fix 'org.eclipse.ui.commands' parsing issues
```
!ENTRY org.eclipse.ui 2 0 2023-02-28 19:28:57.542
!MESSAGE Warnings while parsing the commands from the 'org.eclipse.ui.commands' and 'org.eclipse.ui.actionDefinitions' extension points.
!SUBENTRY 1 org.eclipse.ui 2 0 2023-02-28 19:28:57.542
!MESSAGE Commands should really have a category: plug-in='com.espressif.idf.ui', id='com.espressif.commands.cleanCommand', categoryId='com.espressif.commands.category'
```
Fixes # ([IEP-896](https://jira.espressif.com:8443/browse/IEP-896))
- Launch Espressif-IDE
- Go to Error log
- Look for  'org.eclipse.ui.commands' parsing issues mentioned in ([IEP-896](https://jira.espressif.com:8443/browse/IEP-896)) and there shouldn't be anything on this.
**Test …

IEP-896: Fix 'org.eclipse.ui.commands' parsing issues

---

releng/com.espressif.idf.product/idf.product

Fix espressif.icns path issue in macOS
Fixes # ([IEP-894](https://jira.espressif.com:8443/browse/IEP-894))
In macOS, after launching the workbench we shouldn't see `'Animation Start' has encountered a problem` popup
- Espressif IDE workbench startup

Fix for 'Animation Start' has encountered a problem 

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/CmakeBuildException.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/StringUtil.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/core/IDFCoreLaunchConfigProvider.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/CMakeBuildTab2.java

Launch configuration was not able to restore the custom build folder after closing and reopening the project. As figured out the Instance Scope preference are cleaned up after the closing of the project, so as a solution I decided to move to store preferences in the launch configuration. It also makes code cleaner and allows us to export the launch configuration with all preferences which are set up there.
Also, as part of PR was some related refactoring of the IDFBuildConfiguration class. The goal of the refactoring was to reduce the complexity of the code. After the refactoring, the build command always picks up the last selected build folder (Previously, it required the restart of the eclipse or editing the cmake file)
Was found and fixed the typo: we were using buildCommand instead of …

IEP-886 Launch Configuration does not save custom build folder path

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InputStreamConsoleThread.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/ListInstalledToolsHandler.java

Instead of dumping all the installation output after the process is complete, will read the current state of progress and show it in the console.
https://user-images.githubusercontent.com/8463287/220529540-6fce4bd5-2669-4e04-bf67-6f06b2118afb.mov
Fixes # ([IEP-890](https://jira.espressif.com:8443/browse/IEP-890))
- Espressif Menu > ESP-IDF Tools Manager > Install Tools 
- Observe that console will be updated with the current state instead of dumping everything after it's done.
* OS (Windows,Linux and macOS): macOS
- Install Tools

IEP-890: Show IDF Tools installation status

---

releng/com.espressif.idf.product/idf.product

Add plugin nightly update site to the product repo
Fixes # ([IEP-893](https://jira.espressif.com:8443/browse/IEP-893))
- Go to Help > Install New Software 
- Click on the Manage button
- Check the nightly update site from the list 
- Now nightly update site will appear in the work-with drop-down list
- Choose nightly from the list and you will be able to install IEP nightly build
- Once it's enabled, you should be able to get nightly builds directly using `Help >Check for updates ` also
-Update site

IEP-893: Add plugin nightly update site to the product repo

---

bundles/com.espressif.idf.serial.monitor/META-INF/MANIFEST.MF
bundles/com.espressif.idf.serial.monitor/src/com/espressif/idf/serial/monitor/core/IDFMonitor.java

Opening a serial monitor during debug session makes the idf_monitor reset the board. To avoid this problem, will pass the --no-reset flag to the idf_monitor if there is any active debug session running for the project.
Fixes # ([IEP-898](https://jira.espressif.com:8443/browse/IEP-898))
To reproduce the problem:
- Launch OpenOCD debugging
- Launch esp-idf serial monitor
- Observe the debugging console, and you will find that the "Debug controller was reset" was due to idf_monitor was resetting the board.
```
Info : [esp32.cpu0] Debug controller was reset.
Info : [esp32.cpu0] Core was reset.
Info : [esp32.cpu0] Target halted, PC=0x40007BA1, debug_reason=00000000
Info : [esp32.cpu0] Reset cause (1) - (Power on reset)
Error: [esp32.cpu1] …
```

IEP-898:Opening a serial monitor during debug session makes the idf_monitor to reset the board

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/Messages.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/PortChecker.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/messages.properties
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/Configuration.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/dsf/Launch.java

Checking the availability of ports for debugging. If it's not, we get the next available ports.
Fixes # ([IEP-900](https://jira.espressif.com:8443/browse/IEP-900))
- Test 1:
To test it, I created a simple socket server that occupies the port:
```
public class Server {
public static void main(String[] args) throws IOException {
int port = 3333;
ServerSocket serverSocket = new ServerSocket(port);
System.out.println("Server is listening on port " + port);
while (true) {
Socket socket = serverSocket.accept();
System.out.println("New client connected");
socket.close();
System.out.println("Client disconnected");
}
}
}
```
Then, try to debug with the default debug settings. In the openocd log, you will see that for gdb connection port …

IEP-900 EBV feedback - automatically configure available ports for debugging

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/EspToolCommands.java
bundles/com.espressif.idf.launch.serial.ui/META-INF/MANIFEST.MF
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/Messages.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/NewSerialFlashTargetWizardPage.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/messages.properties
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/EraseFlashDialog.java

Added the feature to select the com port automatically when target is selected.
Also a small text area is added to show user the working while the ports are getting scanned.
The image below is when the dialog is opened.
This image is when the target is selected
Fixes # ([IEP-901](https://jira.espressif.com:8443/browse/IEP-901))
Edit a target and when you select an idf board which is connected already the COM port for that board will be automatically selected.
* ESP-IDF Version: All

IEP-901: Changes to target and ports mapping to help user

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/DirectorySelectionDialog.java

Changing the shell variable to default display shell as the active display and window can be different
Fixes # ([IEP-911](https://jira.espressif.com:8443/browse/IEP-911))
Use jira reference ticket to reproduce and test

IEP-911: Changing the shell variable to default display shell

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/preferences/GlobalMcuPage.java

We must ensure that the user can modify the OpenOCD path through the page we offer in Workspace preferences. Additionally, we need to override not only the OpenOCD.exe path but also the OpenOCD scripts path
Fixes # ([IEP-906](https://jira.espressif.com:8443/browse/IEP-906))
- create a debug configuration
- go to preferences -> Environment -> edit OPENOCD_SCRIPTS variable to non-existing path -> close and apply
- open the debug configuration ->  JTAG flash UI elements are missing now, because we are getting wrong scripts path
- go to preferences -> Espressif -> Global OpenOCD path -> browse openocd bin folder -> apply and close
- open the debug configuration -> now jtag flash UI elements are …

IEP-906 Changing the OpenOCD path does not modify the OpenOCD scripts path

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

run a clean command if getProperty returns empty string
Fixes # ([IEP-904](https://jira.espressif.com:8443/browse/IEP-904))
Test 1:
- Build project, run Clean command
- Clean

IEP-904 Clean Project feature ERROR

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfigurationProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/CMakeBuildTab2.java

To avoid the deadlock issue, I removed the code that created a build configuration using the launch configuration name in the IDFBuildConfigurationProvider's getBuildConfig method. As we store build settings in the working copies of the launch configuration, it is unnecessary to create these build configs anymore, so removing these changes also improved the code's cleanliness and maintainability.
Fixes # ([IEP-917](https://jira.espressif.com:8443/browse/IEP-917))
We need to test items in epic https://jira.espressif.com:8443/browse/IEP-839, to make sure that removing changes didn't break …

IEP-917 Build, Indexer, or the UI can stuck after close and reopen the project/restarting eclipse

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

The project build is getting stuck when there is a plain message which has [] tags but there is no actual file processing mentioned.
Fixes # ([IEP-921](https://jira.espressif.com:8443/browse/IEP-921))
Add #Warning message somewhere in your _main.c file and build a project. The build gets stuck when the warning message is on the build console.
* ESP-IDF Version:master
- Build

Fix: Building project hangs

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/preferences/GlobalMcuPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/ListInstalledToolsHandler.java

I have fixed the git warning issue and possibly this will also fix the git spawn error. Further also reverted to a deprecated method for support with older cdt for PersistentPreferences class
Fixes # ([IEP-878](https://jira.espressif.com:8443/browse/IEP-878))
Using windows sandbox install tools and then click on product information in the Espressif menu there should be no git not found warning now
* ESP-IDF Version: all
* OS (Windows,Linux and macOS): all

IEP-878: Fixing the git warning

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfigurationProvider.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigDelegate.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/controls/SerialSettingsPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/EclipseUtil.java

to show all idf projects, we are checking if a project has an IDF project nature now and passing the active launch target if the default one is missing. Also, to fix the indexer stuck when closing a project, we are returning null in the getCBuildConfiguration method when active launch target is null to avoid exceptions.
Fixes # ([IEP-925](https://jira.espressif.com:8443/browse/IEP-925))
Test 1 (Combo is empty test)
- create a few espressif IDF projects and few C/C++ projects
- Launch Terminal -> ESP-IDF Serial Monitor -> Project name combo should contain only esp-idf projects
Test 2 (launch exception)
- Right-click on project, Run As -> Run Configurations... -> Double click to create a new project and click 'Run' -> No exception …

IEP-925 2.9.1 project combo is empty and launch can throw an exception

---

.github/workflows/ci_release.yml
docs/Espressif-IDE.md

IEP-932:Create /latest links to the espressf-ide downloads for each release version
Fixes # ([IEP-932](https://jira.espressif.com:8443/browse/IEP-932))
Below links should reflect the latest stable version after each release is published
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-win32.win32.x86_64/latest
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-macosx-cocoa-x86_64/latest
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-macosx-cocoa-aarch64/latest
https://dl.espressif.com/dl/idf-eclipse-plugin/ide/Espressif-IDE-linux.gtk.x86_64/latest
- Download links mentioned above

IEP-932:Create /latest links to the espressf-ide downloads for each release version

---

bundles/com.espressif.idf.sdk.config.core/src/com/espressif/idf/sdk/config/core/server/JsonConfigServer.java

adding -B <build_folder> arguments to confserver command
Fixes # ([IEP-934](https://jira.espressif.com:8443/browse/IEP-934))
Test 1:
- create a new project, set a custom build folder, and build
- open sdkconfig file -> cmake ninja runs in the custom build folder
Test 2:
- select another configuration without the custom build folder, build
- open sdkconfig file -> cmake ninja runs in default build folder
- sdkconfig
- build folder

IEP-934 idf.py confserver always runs in default build folder

---

releng/com.espressif.idf.product/idf.product

Set the default user workspace to the /USER_HOME/workspace
Fixes # ([IEP-xxx](https://jira.espressif.com:8443/browse/IEP-xxx))
- Bugfix
Test Case:
- Download Espressif-IDE with this PR
- Observe the workspace selection dialog during the launch, it should set a default workspace to /USER_HOME/workspace
* ESP-IDF Version: master
- Espressif-IDE startup workspace selection dialog

Fix: Add default user workspace

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

removing the launch bar listener before updating the launch bar and adding it back just before adding the last configuration.
Fixes # ([IEP-858](https://jira.espressif.com:8443/browse/IEP-858))
Here are steps to reproduce the issue on master. This use case should be fixed on this branch:
1. Create a new project,  set an esp32 target, and build
2. Create a new launch configuration, set the esp32s2 target
3. close/reopening project -> see default configuration with esp32 target, but notifier says that target changed from esp32s2 from esp32. 
- Launch target has changed notification msg

IEP-858 Incorrect target change notification after eclipse restart

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFLaunchConstants.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/plugin.properties
bundles/com.espressif.idf.debug.gdbjtag.openocd/plugin.xml
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/DefaultAppResolver.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/DynamicVariableResolver.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/dsf/LaunchConfigurationDelegate.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/preferences/DefaultPreferences.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/Messages.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabMain.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/messages.properties
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/util/ESPFlashUtil.java

Fixed jtag flashing issue with custom build folder by modifying ESPFlashUtil class and getting custom build folder from project. Also, I've added a Launch Config selector to the main debug config tab, making the build process more intuitive with the debug config. Essentially, we are linking our run configuration to the debug configuration so that we can get all the necessary build settings: 
Fixes # ([IEP-927](https://jira.espressif.com:8443/browse/IEP-927))
Test 1:
- create a new project
- …

IEP-927 JTAG and Debugging for Custom Build Folder doesn't work

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/EclipseIniUtil.java

Changes to eclipse ini utility class to handle single line parameters in configs for language change. The ide was not able to open due to wrong configuration format of the file
Fixes # ([IEP-931](https://jira.espressif.com:8443/browse/IEP-931))
Remove everything in the espress-ide.ini file only keep the -vm argument to point to the vm and then change language the ide should launch after language change with only vm config in ini file

IEP-931: espressif-ide:couldn't open after changing the language config

---

releng/com.espressif.idf.target/com.espressif.idf.target.target

Added the required slf4j api for the resolution of errors related to egit
Fixes # ([IEP-956](https://jira.espressif.com:8443/browse/IEP-956))
Building locally and seeing if any errors are seen at the start related to IDE.
* OS (Windows,Linux and macOS): Windows

IEP-956: JGIT EGIT failing to load due to missing slf4j with latest release

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java

fixed `Variables...` button listener for Arguments group
Fixes # ([IEP-950](https://jira.espressif.com:8443/browse/IEP-950))
Test 1:
- Edit launch configuration -> click on Variables... button near the Arguments field
- Select any variable
- Variable should be insert into text field
Test 2:
- Repeat Test 1 with different Flash Over (JTAG, UART, DFU)
Test 3:
- OK and reopen
- Launch configuration

IEP-950 `Variables...` button doesn't work for Arguments group

---

bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigProvider.java

added check for a null target for supports() method
Fixes # ([IEP-951](https://jira.espressif.com:8443/browse/IEP-951))
Test 1:
- restart eclipse, check log -> shouldn't be a message:!MESSAGE Error: Cannot invoke "org.eclipse.debug.core.ILaunchConfiguration.getType()" because "configuration" is null 
- target bar

IEP-951 MESSAGE Error:... "configuration" is null when restart eclipse

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/dsf/GdbServerBackend.java
bundles/com.espressif.idf.serial.monitor/src/com/espressif/idf/serial/monitor/core/LocalTerminal.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/EspresssifPreferencesPage.java

Our usage for espressif preference page values looks like this:
1. `Platform.getPreferencesService().getInt(UIPlugin.PLUGIN_ID, Activator.GDB_SERVER_LAUNCH_TIMEOUT, fGdbServerLaunchDefaultTimeout, null);
`
2. `int numberOfRows = Platform.getPreferencesService().getInt(UIPlugin.PLUGIN_ID, EspresssifPreferencesPage.NUMBER_OF_LINES, EspresssifPreferencesPage.DEFAULT_SERIAL_MONITOR_NUBMER_OF_LINES, null); `
3. `int numberOfCols = Platform.getPreferencesService().getInt(UIPlugin.PLUGIN_ID, EspresssifPreferencesPage.NUMBER_OF_CHARS_IN_A_LINE, EspresssifPreferencesPage.DEFAULT_SERIAL_MONITOR_NUMBER_OF_CHARS_IN_LINE, null);`
Fixes # ([IEP-966](https://jira.espressif.com:8443/browse/IEP-966))
changed preference store for the Espressif preference page accordingly to these calls;
Please delete …

IEP-966 openocd server always has default timeout 25 seconds

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/messages.properties
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

Checking the esp_idf.json timestamp for env initialization
Fixes # ([IEP-952](https://jira.espressif.com:8443/browse/IEP-952))
Use the tests in the following PR (https://github.com/espressif/idf-eclipse-plugin/pull/662). 
Also try to install the tools in the IDE after the IDE is initialized via esp_idf.json file and try to close and reopen the IDE to see if the message popup appears. The original jira ticket also contains links to the forum and github issues.
* ESP-IDF Version: Any
* OS (Windows,Linux and macOS): Windows only (Since installer is currently given for Windows only)

IEP-952: Espressif IDE popup for old tool versions popping up after installing tools via IDE

---

releng/com.espressif.idf.target/com.espressif.idf.target.target
tests/com.espressif.idf.ui.test/META-INF/MANIFEST.MF

looks like org.slf4j.api was removed from the egit dependencies

IEP-984 org.slf4j.api dependency cannot be resolved

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/IDFProjectNature.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/IDFDebugLaunchDescriptorType.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabMain.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/EclipseUtil.java

The project field couldn't be pre-filled during creating a debug configuration. This case is fixed in this PR. The code is extracted to UI util class, so it can be reused for launch configuration also.
Fixes # ([IEP-958](https://jira.espressif.com:8443/browse/IEP-958))
Test 1:
creating debug configurations with different cases:
- Select the project in the project explorer, and create a new debug configuration. Project in debug configuration == selected project in the project explorer
- Select the closed project in the project explorer, and create a new debug configuration. Project in debug configuration == next available project in the project explorer
- restart eclipse, and create a …

IEP-958 New debug configuration fields should be pre-filled

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/NvsBeanValidator.java
tests/com.espressif.idf.core.test/META-INF/MANIFEST.MF
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/util/test/NvsBeanValidatorTest.java

changed validation for integers, so only decimals are correct now. Also added test coverage for NvsBeanValidator.
Fixes # ([IEP-977](https://jira.espressif.com:8443/browse/IEP-977))
Test 1:
- Open Nvs table editor
- Add a column with type data and some integer encoding.
- write different integer formats, only decimal in correct range should pass validation
- NVS table editor

IEP-977 NVS Table editor - validation on integer types is incorrect

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/BigIntDecoder.java
tests/com.espressif.idf.core.test/META-INF/MANIFEST.MF
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/util/test/BigIntDecoderTest.java

Added test coverage for BigIntDecoder class. Also, during the test I found bug, so I fixed it in this PR. The bug was in the incorrect decoding of hex, and octal values without a sign.
Fixes # ([IEP-976](https://jira.espressif.com:8443/browse/IEP-976))
BigIntDecoder is using for validating data in the NVS table, so to test it:
- Open the NVS table editor
- Add a new row 
- type some name in a new row and select 'data' as a type 
- select encoding, for example u8 and type hex/oct/dec numbers for example 0xFF - should be ok, 0xFFF - out of range for u8, FF - incorrect format
* OS …

IEP-976 Test coverage for BigIntDecoder

---

tests/com.espressif.idf.core.test/META-INF/MANIFEST.MF
tests/com.espressif.idf.core.test/pom.xml
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/test/InputStreamThreadReaderTest.java

InputStreamThrea covered by unit tests
Fixes # ([IEP-961](https://jira.espressif.com:8443/browse/IEP-961))
No changes to existing code, so just run junit tests

IEP-961 Test InputStreamThread

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/logging/Logger.java
tests/com.espressif.idf.core.test/META-INF/MANIFEST.MF
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/test/OutputStreamThreadTest.java

test coverage for OutputStreamThread class
Fixes # ([IEP-962](https://jira.espressif.com:8443/browse/IEP-962))
No changes in code, so just run JUnit tests;
- Junit tests

IEP-962 Test coverage for OutputStreamThread

---

tests/com.espressif.idf.core.test/META-INF/MANIFEST.MF
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/test/ZipUtilityTest.java

Test coverage for ZipUtility class
Fixes # ([IEP-969](https://jira.espressif.com:8443/browse/IEP-969))
run junit tests
junit tests

IEP-969 Test coverage for ZipUtility

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/DefaultBoardProvider.java
bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/ui/TabDebugger.java
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/test/DefaultBoardProviderTest.java

Provided default boards for C3/S3 chips
Fixes # ([IEP-959](https://jira.espressif.com:8443/browse/IEP-959))
Test 1:
- create a new debug/launch configuration -> select C3/S3 target. Default board with via builtin USB-JTAG should be selected
Test 2:
- select any board other then C3/S3 -> default board is first from the list
- Launch configuration with flash via the JTAG option
- Debug configuration

IEP-959 Debugger tab for C3/S3 chips set "via builtin USB-JTAG" option by default

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/HintsUtil.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/HintsView.java
tests/com.espressif.idf.core.test/resources/hints.yml
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/util/test/HintsUtilTest.java

added test coverage for HintsUtil class
Fixes # ([IEP-982](https://jira.espressif.com:8443/browse/IEP-982))
- run tests
- tests

IEP-982 Test coverage for HintsUtil

---

bundles/com.espressif.idf.branding/META-INF/MANIFEST.MF
bundles/com.espressif.idf.branding/pom.xml
features/com.espressif.idf.feature/feature.xml
features/com.espressif.idf.feature/pom.xml
releng/com.espressif.idf.configuration/pom.xml
releng/com.espressif.idf.product/idf.product
releng/com.espressif.idf.product/pom.xml
releng/com.espressif.idf.update/pom.xml
tests/com.espressif.idf.core.test/pom.xml

Bump version to 2.11.0
Fixes # ([IEP-1005](https://jira.espressif.com:8443/browse/IEP-1005))
Update version number to 2.11.0
- Verify Espressif-IDE About version number
- Verify Update site version number
- Verify Espressif-IDE About version number
- Verify Update site version number
- Verify the generated installers version number

Bump version to 2.11.0

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/ActiveLaunchConfigurationProvider.java
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/internal/SerialFlashLaunchConfigProvider.java
tests/com.espressif.idf.core.test/META-INF/MANIFEST.MF
tests/com.espressif.idf.core.test/src/com/espressif/idf/core/test/ActiveLaunchConfigurationTest.java

The problem was that LaunchBarManager could return null because it was not yet initialized during the eclipse starting phase. 
Fixes # ([IEP-1002](https://jira.espressif.com:8443/browse/IEP-1002))
Test 1
- run build -> during indexer phase restart eclipse -> after restarting open error log -> should be no NPE exception there
Test 2
- create/clean a workspace -> install tools -> create new project -> create new launch configuration  -> should be created correctly. Verify that there is no such error:
- build
- IDFBuildConfiguration

GH #798: At execution Espressif-IDE getting 'Cannot invoke "org.eclipse.debug.core.ILaunchConfiguration.getType()" because "configuration" is null'

---

features/com.espressif.idf.feature/feature.xml
releng/com.espressif.idf.update/category.xml

Update site name has changed from "Espressif IDF" to "ESP-IDF Eclipse Plugin" and description has updated.
Fixes # ([IEP-1086](https://jira.espressif.com:8443/browse/IEP-1086))
- Use the PR update site
- Verify that update site name has changed from "Espressif IDF" to "ESP-IDF Eclipse Plugin" and also description has updated.
* OS (Windows,Linux and macOS): macOS
- Update site

fix: IEP Update site naming convention

---

bundles/com.espressif.idf.core/pom.xml
releng/com.espressif.idf.target/com.espressif.idf.target.target

As eclipse [2023-12](https://download.eclipse.org/eclipse/updates/4.29/) R-builds is available , IEP plugin builds are failing due to dependency issues and API issues. In this PR, will try to strict our CI builds to Eclipse 2023-09 builds until we have the IEP support for the Eclipse 2023-12.
Fixes # ([IEP-1125](https://jira.espressif.com:8443/browse/IEP-1125))
Verify the master build is successful or not, see if they have created with the Eclipse CDT 2023-09 buid.
- Update site Installation
- Espressif-IDE Installation and update

ci: Restrict IEP plugin build with 2023-09

---

bundles/com.espressif.idf.core/plugin.xml

Fixed debugger patterns to get correct gdb executables. The problem was, that without "$" at the end we could get the wrong executable, for example, bin\xtensa-esp32-elf-gdb-3.7.exe, etc.
Fixes # ([IEP-1135](https://jira.espressif.com:8443/browse/IEP-1135))
Test 1:
try to debug with different targets
Test 2:
check the actual executable path in the debugger tab for different targets 
- Debugger tab

IEP-1135 Incorrect default gdb executable for RISCV targets

---

releng/com.espressif.idf.product/pom.xml

Update macOS application display name from Espressif-ide to  Espressif-IDE
- download espressif-ide from PR
- verify application display name
- dmg file

fix: Update macOS application display name

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

- Test A
- Test B
- Component 1
- Component 2

fix: Update clangd troublshooting tip

---

.github/workflows/ci_beta.yml

- Test A
- Test B
- Component 1
- Component 2

fix: for keychain lock issue while during notorization arm64 dmg

---

releng/com.espressif.idf.target/com.espressif.idf.target.target

Upgrade cmakeed plugin to CMakeEd-1.24.1 from 1.17.0
Fixes # ([IEP-1459](https://jira.espressif.com:8443/browse/IEP-1459))
- Test A
- Test B
- Component 1
- Component 2

chore: Upgrade cmakeed plugin to CMakeEd-1.24.1 from 1.17.0

---

.github/workflows/ci_release.yml

Fix ci release

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/GlobalModalLock.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/LaunchBarListener.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/EspressifToolStartup.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/watcher/EimJsonUiChangeHandler.java

Added global modal lock to avoid simultaneous modals. 
https://github.com/user-attachments/assets/f2589094-e487-4f0e-a3af-ad4f67ad6995
Fixes # ([IEP-1584](https://jira.espressif.com:8443/browse/IEP-1584))
build the project on the master -> change the target -> click no -> close the IDE -> change the branch to the 4.0.0 release -> open without cleaning the environment -> verify that no two modals at the same time 
- Component 1
- Component 2

IEP-1584 Avoid Simultaneous Modals on Old Config Detection

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/tools/EimIdfConfiguratinParser.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/manager/pages/ESPIDFMainTablePage.java

An exception occurs if EIM is opened from a fresh IDE launch and closed before the tool installation completes and eim.json is generated.
java.lang.NullPointerException: Cannot invoke "com.espressif.idf.core.tools.vo.EimJson.getIdfInstalled()" because "com.espressif.idf.ui.tools.manager.pages.ESPIDFMainTablePage.eimJson" is null
at com.espressif.idf.ui.tools.manager.pages.ESPIDFMainTablePage.refreshEditorUI(ESPIDFMainTablePage.java:195)
at com.espressif.idf.ui.tools.EimButtonLaunchListener.lambda$1(EimButtonLaunchListener.java:105)
Fixes # ([IEP-1602](https://jira.espressif.com:8443/browse/IEP-1602))
Open fresh workspace → launch EIM via IDE → close EIM before tools install -> no …

IEP-1602 Prevent Exception When EIM Closes Before eim.json Is Created
