espressif/idf-eclipse-plugin

README.md

These are some relatively minor rewordings that I felt were worthwhile. While reading through the README, I encountered a few places where the grammar was just a bit off or a sentence appeared malformed.

README rewording (IEP-179)

---

bundles/com.espressif.idf.core/META-INF/MANIFEST.MF
bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

https://jira.espressif.com:8443/browse/IEP-271

Fix: No esp launch target found error while debugging (IEP-272)

---

bundles/com.espressif.idf.ui/plugin.xml

issue: https://jira.espressif.com:8443/browse/IEP-280?jql=labels%20%3D%20good-first-issue

added separator to the Help menu (IEP-290)

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeAnalysisEditor.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeOverviewComposite.java

Now ESP-IDF Application size analysis editor is showing the project name

IEP-187: Add project name to size analysis editor (IEP-291)

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

IEP-296: Show total time took for compilation / build (IEP-297)

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewIDFProjectWizard.java

new created project is selected in project explorer like this:

IEP 298 project selection has to move to the new created project (IEP-304)

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeAnalysisEditor.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/AbstractTemplatesSelectionPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/TemplateListSelectionPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/TemplatesManager.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewIDFProjectWizard.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/WizardNewProjectCreationPage.java

Added project name text field with the label. When the option to select a template is available, the project name is based on the selected template. Validation of project name based on validation from main page. Few cases of not passed validation:
- **Case 1** - spaces in the name :
- **Case 2** - project name already exists:
When validation is not passed successfully Finish button is unavailable. 
Also, when the project name is changed on the templates page it will be also changed on the main page.

IEP 293 allow to enter project name in the templates wizard (IEP-295)

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/AbstractTemplatesSelectionPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/TemplateListSelectionPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/templates/messages.properties

added search filter based on PatternFilter, which is searching elements in the tree structure

Added search tree filter to templates (IEP-300)

---

bundles/com.espressif.idf.sdk.config.ui/src/com/espressif/idf/sdk/config/ui/SDKConfigurationEditor.java
bundles/com.espressif.idf.sdk.config.ui/src/com/espressif/idf/sdk/config/ui/SDKConfigurationFilter.java

Now filtering based not only on the visible tree elements but on child elements also

Iep 53 imrpove filtering in sdkconfig editor

---

README.md

https://jira.espressif.com:8443/browse/DOC-827

IEP-316: Plugin support for Eclipse 2020-09(4.17)

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java

Find python path from IDF_PYTHON_ENV_PATH CDT build env variable

IEP-356: Fix for python executable path

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/resources/ResourceChangeListener.java

Cleanup the build folder after copy/rename/import as it contains old project artifacts like cmakecache.txt which causes build failure.
Test cases: 
create a new project > build > rename > build renamed project - passed
create a new project > rename > build renamed project - passed
copy some built project > delete old project > build copied project - passed
copy non-built project > build copied project - passed
copy some built project > built copied project - passed (make sure that new project is built)
create new project > build it > delete from workspace > import to a workspace with new name > build it again - passed
create new project > delete from workspace > import to a workspace with new name >build it - passed
tested on Windows 10 and macOS

IEP-378 deleting build folder after rename/copy/import

---

bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/connector/SerialConnector.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/connector/SerialSettings.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/controls/SerialConfigPanel.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/controls/SerialSettingsPage.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/launcher/SerialLauncherDelegate.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/nls/Messages.java
bundles/com.espressif.idf.terminal.connector.serial/src/com/espressif/idf/terminal/connector/serial/nls/Messages.properties

The project name field was added to the ESP-IDF Serial monitor

IEP-393: show a list of projects if there is no project selection found

---

bundles/com.espressif.idf.ui/plugin.xml
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/NewComponentHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewComponentWizardPage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/messages.properties

Fixed NPE, added combo button which allows to select project from the workspace

IEP-403 Fixing NPE in the new component wizard

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/wizard/NewComponentWizardPage.java

Added a default value for the project field in the create-component wizard.

IEP-411 add a default value for project 

---

bundles/com.espressif.idf.sdk.config.ui/src/com/espressif/idf/sdk/config/ui/SDKConfigurationEditor.java

https://jira.espressif.com:8443/browse/IEP-414

IEP-414: Invalid thread access error while closing sdkconfig editor

---

README.md
README_CN.md

This PR:
- Updates to the readme.md file
- Adds a new readme_CN.md file

Provide translation to readme file (IEP-422)

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeDataManager.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/size/IDFSizeOverviewComposite.java

IEP-240: Fix for Application size analysis editor

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/InitializeToolsStartup.java

This is to avoid issues with the user settings are getting overridden by the esp_idf.json settings every time eclipse launches.

Fix: load esp_idf.json only once for workspace

---

.gitlab-ci.yml
bundles/com.espressif.idf.branding/META-INF/MANIFEST.MF
bundles/com.espressif.idf.branding/pom.xml
features/com.espressif.idf.feature/feature.xml
features/com.espressif.idf.feature/pom.xml
releng/com.espressif.idf.update/pom.xml

These are the files we will change during the version update!

Update to version v2.1.1

---

features/com.espressif.idf.feature/feature.xml
releng/com.espressif.idf.target/com.espressif.idf.target.target
releng/pom.xml

Fix for the below issues reported
https://github.com/espressif/idf-eclipse-plugin/issues/299
https://github.com/espressif/idf-eclipse-plugin/issues/260

IEP-417: Eclipse 4.20 support and fix installation issues

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/install/IDFDownloadPage.java

IEP-495: added path validation for downloaded esp-idf

---

bundles/com.espressif.idf.branding/build.properties
bundles/com.espressif.idf.branding/plugin.properties
bundles/com.espressif.idf.branding/plugin.xml
bundles/com.espressif.idf.branding/plugin_customization.ini
bundles/com.espressif.idf.ui/META-INF/MANIFEST.MF
bundles/com.espressif.idf.ui/index.html
bundles/com.espressif.idf.ui/plugin.xml
releng/com.espressif.idf.product/build.properties
releng/com.espressif.idf.product/idf.product
releng/com.espressif.idf.product/plugin_customization.ini

- Update About Text
- Set default workspace directory
- Fix welcome page issues
- Update VM Arguments
- Set C++ as default perspective 
- Add Welcome page icon

Eclipse RCP updates #3

---

README.md

To help https://github.com/espressif/idf-eclipse-plugin/issues/395

IEP-561: Add how to build locally instructions

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/GenericJsonReader.java
bundles/com.espressif.idf.sdk.config.core/src/com/espressif/idf/sdk/config/core/KConfigMenuProcessor.java
bundles/com.espressif.idf.sdk.config.core/src/com/espressif/idf/sdk/config/core/server/JsonConfigServerRunnable.java

Replace FileReader with BufferReader and close the streams

IEP-563: Unable to delete a build directory

---

bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java

fix for launch configuration is not saved after editing

IEP-617: v2.3.0 Launch configuration can not saved

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/util/IDFUtil.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/util/ESPFlashUtil.java

Extended openocd version check for jtag flashing

IEP-302 IDF Tools version check

---

bundles/com.espressif.idf.ui/OSGI-INF/l10n/bundle.properties
bundles/com.espressif.idf.ui/build.properties
bundles/com.espressif.idf.ui/plugin.xml

Changing back to the original handler and icon for the menu item

IEP-629: ESP-IDF Eclipse Plugin Guide link fix

---

bundles/com.espressif.idf.debug.gdbjtag.openocd/src/com/espressif/idf/debug/gdbjtag/openocd/dsf/GdbServerBackend.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/preferences/messages.properties

- Changed qualifier for gdb server launch timeout preference
- typo fix from ms to s

IEP-640: Unable to debug project on beta version 2.4.1

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java

User not able to install due to invalid thread access so added the syn call to the default display

Display sync added for invalid message thread access

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/InstallToolsHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/messages.properties

This PR contains requested changes to this PR https://github.com/espressif/idf-eclipse-plugin/pull/516

IEP-684: Refactoring Install tools handler class

---

tests/com.espressif.idf.ui.test/src/com/espressif/idf/ui/test/executable/cases/launchconfiguration/LaunchBarCDTConfigurationsTest.java

The issue for the test failure is still not clear and since the builds are tested through other flows as well we are commenting out the test that is failing

IEP-696: Test:LaunchBarCDTConfigurationsTest intermittently failing

---

bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/core/IDFCoreLaunchConfigProvider.java
bundles/com.espressif.idf.launch.serial.core/src/com/espressif/idf/launch/serial/core/IDFLaunchDescriptorType.java
bundles/com.espressif.idf.launch.serial.ui/META-INF/MANIFEST.MF
bundles/com.espressif.idf.launch.serial.ui/src/com/espressif/idf/launch/serial/ui/internal/CMakeMainTab2.java
bundles/com.espressif.idf.ui/META-INF/MANIFEST.MF
bundles/com.espressif.idf.ui/OSGI-INF/l10n/bundle.properties
bundles/com.espressif.idf.ui/plugin.xml
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/DeleteResourceWizard.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/Messages.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/messages.properties
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/DeleteResourceHandler.java
tests/com.espressif.idf.ui.test/src/com/espressif/idf/ui/test/executable/cases/project/NewEspressifIDFProjectTest.java
tests/com.espressif.idf.ui.test/src/com/espressif/idf/ui/test/operations/EnvSetupOperations.java
tests/com.espressif.idf.ui.test/src/com/espressif/idf/ui/test/operations/ProjectTestOperations.java

Added an option to delete all configurations related to the project being deleted. 
To verify create a few projects and multiple configurations to these projects
Right-click on the project in project explorer-> Delete
after the deletion

IEP-690: Add an option to delete all configurations related to the project being deleted.

---

docs/OpenOCD Debugging.md

Update OpenOCD Debugging.md

---

.github/workflows/nightly.yml

Fix nightly build issues
https://dl.espressif.com/dl/idf-eclipse-plugin/updates/nightly/
-  Download espressif-ide v2.5.0
-  Install nightly build through the update site https://dl.espressif.com/dl/idf-eclipse-plugin/updates/nightly/
-  Verify if it's getting installed.
- Update site

Fix nightly issues

---

README.md
releng/index.html

Update readme.md and index.html on nightly builds
-  documentation update
Preview readme.md and index.html

doc: Update readme.md on nightly builds

---

README.md
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/dialogs/HintsView.java

Add documentation about hints viewer

IEP-757: Add documentation about hints viewer

---

FAQ.md

esp-adf configure doc

---

FAQ.md

SSL certification download error faq added

doc: SSL certification download error faq

---

NewAndNoteworthy/README.md
bundles/com.espressif.idf.branding/META-INF/MANIFEST.MF
bundles/com.espressif.idf.branding/pom.xml
features/com.espressif.idf.feature/feature.xml
features/com.espressif.idf.feature/pom.xml
releng/com.espressif.idf.product/idf.product
releng/com.espressif.idf.product/pom.xml
releng/com.espressif.idf.update/pom.xml

- Test A
- Test B
- Component 1
- Component 2

bump to v2.7.0

---

README.md
WORKAROUNDS.md

added documentation about how to use the clang toolchain

Documentation update: How to use the clang toolchain

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/update/AbstractToolsHandler.java

Added an additional check, if founded versions are 3.6 and higher
Fixes # ([IEP-862](https://jira.espressif.com:8443/browse/IEP-EP-862))
Test 1:
- Install multiple versions of python on Windows so that these versions are in the Windows registry
- Try installing tools from eclipse. 
- List install tools -> no repeatedly ask to install missing tools
* OS (Windows):
- Install Tools command
- List Installed Tools command

IEP-862 Repeatedly ask to install some missing tools

---

README.md

Documentation update for NVS and Partition Table editors 
Fixes # ([IEP-859](https://jira.espressif.com:8443/browse/IEP-859))

IEP-859 Create a documentation for NVS and Partition editors

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

Show compilation progress in the IDE status bar based on the number of files compiled
https://user-images.githubusercontent.com/8463287/220529982-a1ab4e7d-4141-45d3-bff4-2fb0233a4ac4.mp4
Fixes # [IEP-889](https://jira.espressif.com:8443/browse/IEP-889)
- Build a project
- See the progress status appearing for the build on the IDE status bar
* OS (Windows,Linux and macOS): macOS
- Build

IEP-889: Show build progress status

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/install/GitProgressMonitor.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/GitWizardRepProgressMonitor.java

Compatible fixes with Eclipse 2022-03 JGIT plugin
Fixes # ([IEP-948](https://jira.espressif.com:8443/browse/IEP-948))
- Install ESP-IDF From Eclipse and make sure there is no error reported
- Update ESP-IDF Master from Eclipse and make sure there is no error reported
- ESP-IDF Install
- ESP-IDF maser update

Fix: Compatible fixes with Eclipse 2022-03 JGIT plugin

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/handlers/UpdateEspIdfHandler.java

Looks like the problem happens because the update command in the JGIT doesn't fetch by default. Also, I took a deeper look into the source code and it seems submodules not updating recursive, so I had to fix it also.
Fixes # ([IEP-926](https://jira.espressif.com:8443/browse/IEP-926))
- Install esp-idf master
- Espressif -> ESP-IDF Tools Manager -> Update esp-idf master
- esp-idf from master
- esp-idf update command

IEP-926 GH #740: An internal error occurred during: "Updating ESP-IDF master...".

---

README.md

- Test A
- Test B
- Component 1
- Component 2

Update espressif-ide-setup-2.10.0-with-esp-idf-5.0.1.exe link

---

bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/ToolsInstallationHandler.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/wizard/pages/InstallPreRquisitePage.java
bundles/com.espressif.idf.ui/src/com/espressif/idf/ui/tools/wizard/pages/ManageToolsInstallationWizardPage.java

Bug fix for recommended button in Tools Installation Wizard
Fixes # ([IEP-975](https://jira.espressif.com:8443/browse/IEP-975))
Please use the reported flow to verify
* ESP-IDF Version: Any
* OS (Windows,Linux and macOS): Any

IEP-975: Bug fix for recommended button in Tools Installation Wizard

---

bundles/com.espressif.idf.branding/about.properties

Update Espressif license info
Checkout About Espressif-IDE 
- Component 1
- Component 2

 Update Espressif license info

---

bundles/com.espressif.idf.ui/META-INF/MANIFEST.MF
releng/com.espressif.idf.target/com.espressif.idf.target.target

Add Eclipse Market client to the espressif-ide
Fixes # ([IEP-997](https://jira.espressif.com:8443/browse/IEP-997))
Help > Eclipse Market Place
Eclipse Market place

Add Eclipse MarketPlace to the espressif-ide

---

.github/workflows/ci_beta.yml

- Test A
- Test B
- Component 1
- Component 2

feat: Add beta builds to workflows

---

.github/workflows/ci_beta.yml

- Test A
- Test B
- Component 1
- Component 2

fix: remove - arg from base64 command

---

bundles/com.espressif.idf.core/src/com/espressif/idf/core/build/IDFBuildConfiguration.java

- Test A
- Test B
- Component 1
- Component 2

fix: cleanup the clangd console messages

---

releng/com.espressif.idf.target/com.espressif.idf.target.target
releng/com.espressif.idf.update/category.xml

- Test A
- Test B
- Component 1
- Component 2

fix update site issues with the org.commonmark

---

.github/workflows/ci_release.yml

Fix for ci release.yml links fixed and scripts updated

Fix ci release

---

bundles/com.espressif.idf.branding/META-INF/MANIFEST.MF
features/com.espressif.idf.feature/feature.xml
releng/com.espressif.idf.configuration/pom.xml
releng/com.espressif.idf.product/idf.product

- Test A
- Test B
- Component 1
- Component 2

fix: bump version to v4.0.0
